version: "3"

services:
  fastapi:
    build: src/fastapi-code/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: src/streamlit-code/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_networks:
    driver: bridge
