name: linter

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./tasks
  linting:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7.5]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install bandit black mypy pycodestyle pydocstyle pylint pytest safety flake8

      - name: Run black --check ./src
        run: black --check ./src

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          mypy: true

      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black ./src
          git config --global user.name 'JayThibs'
          git config --global user.email 'thibo.jacques@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push

      # - name: Linting
      #   run: make lint
